version: '3'

services:
  web:
    build:
      context: ./
      target: dev
    volumes:
      - .:/src
      - /src/node_modules
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
    networks:
      - web-network
    depends_on:
      - postgres
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-demo_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-admin}
      POSTGRES_DB: demo_store
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
       - ./db/01-init.sh:/docker-entrypoint-initdb/01-init.sh
    networks:
      - web-network
    restart: unless-stopped
networks:
  web-network:
    driver: bridge

volumes:
    postgres: